import { test, expect } from "@playwright/test";
import { LoginPage } from "./pages/LoginPage";
import { DashboardAdminPage } from "./pages/DashboardPage";
import { prisma } from "../src/lib/prisma"; // Direct DB access for verification

/**
 * Critical Path Tests
 * ===================
 * Focuses on high-value user flows and database integration.
 * Replaces fragile UI tests with robust logic checks.
 */

test.describe("Public Pages Smoke Test", () => {
  test("Homepage loads correctly", async ({ page }) => {
    await page.goto("/");
    await expect(page).toHaveTitle(/SMP IP YAKIN/i);
    await expect(page.locator("nav")).toBeVisible();
  });

  test("Login page loads", async ({ page }) => {
    await page.goto("/login");
    // Updated selector to match ID
    await expect(page.locator('#username')).toBeVisible();
  });
});

test.describe("Admin Critical Flow", () => {
  let loginPage: LoginPage;
  let dashboardPage: DashboardAdminPage;
  const uniqueId = Date.now().toString();
  const newsTitle = `Automation Test News ${uniqueId}`;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    dashboardPage = new DashboardAdminPage(page);
    await loginPage.loginAs("admin");
  });

  test("Admin can create news and it persists to DB", async ({ page }) => {
    // 1. Navigate to News Management
    await dashboardPage.gotoNews();

    // 2. Open "Add News" Modal
    const addButton = page.locator('button:has-text("Add News")');
    await expect(addButton).toBeVisible();
    await addButton.click();

    // 3. Fill Form
    await page.fill('input[name="title"]', newsTitle);
    await page.fill('textarea[name="content"]', "This is a test content generated by automation.");

    const categorySelect = page.locator('select[name="kategori"]');
    if (await categorySelect.isVisible()) {
        await categorySelect.selectOption("ACTIVITY");
    }

    // 4. Submit
    await page.click('button:has-text("Save News")');

    // 5. Wait for Result (Success or Failure)
    // We try to find ANY toast message to understand what happened
    // React Hot Toast usually puts text in a div
    const toastMessage = page.locator('div[role="status"]');
    // Or generic text search for "created" or "Failed"

    try {
        await expect(page.locator('text=News created')).toBeVisible({ timeout: 10000 });
    } catch (e) {
        // If success not found, check for error
        const content = await page.content();
        console.log("DEBUG: Page content after submit failure:");
        // Print snippet around "Failed" or "Error"
        if (content.includes("Failed")) {
             console.log("Found 'Failed' text on page.");
        }

        // Check if DB has it anyway?
        const newsItem = await prisma.news.findFirst({
            where: { title: newsTitle }
        });
        console.log("DEBUG: DB Check result:", newsItem);

        throw e; // Re-throw the error
    }

    // 6. VERIFY IN DATABASE
    await expect(async () => {
        const newsItem = await prisma.news.findFirst({
            where: { title: newsTitle }
        });
        expect(newsItem).not.toBeNull();
        expect(newsItem?.title).toBe(newsTitle);
    }).toPass({ timeout: 5000 });

    // 7. Cleanup
    await prisma.news.deleteMany({
        where: { title: newsTitle }
    });
  });
});

test.describe("Security & RBAC", () => {
  test("Student cannot access Admin Dashboard", async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.loginAs("siswa"); // uses siswa001 / admin123

    // Try to force navigate
    await page.goto("/dashboard-admin");

    // Should be redirected
    await expect(page).not.toHaveURL(/dashboard-admin/);
  });
});
